### ISSUE TITLE
It doesn't work in Premake5

### ISSUE THREAD

**Issue by Geequlim** [TurkeyMan/premake-cmake#1]
Hello TurkeyMan , thanks for your scripts.

There are some probelms in this module.
- _cmake.lua : 28 , here you may forget a quote for "clang".

I add the quote and required _cmake module in my script but it doesn't work when I execute

``` bash
$ premake5 cmake
```

Here is the outputed message

``` bash
$ premake5 cmake
$ Building configurations...
$ Running action 'cmake'...
$ Error: /Users/Geequlim/.premake/cmake/_cmake.lua:35: attempt to call field 'getmakefilename' (a nil value)
```

My version of premake is **premake-5.0-alpha4  macosx**

**Comment by TurkeyMan** [comment]
You're right. It's still work-in-progress. I'll finish it some day.

**Comment by greshnoff** [comment]
hi, any update?

**Comment by TurkeyMan** [comment]
i haven't worked on it. my own need for this is gone. sorry!

**Comment by Geequlim** [comment]
@greshnoff Try here https://github.com/Geequlim/premake-modules or https://github.com/Geequlim/genproject.

I have switched to scons :)
